acoustic3d_edge_horizontal:
  ros__parameters:
    use_sim_time: false
    sonar:
      topic: "/blueview_message_polar"
      threshold: 60.
      min_range: 0.7
      max_range: 7.
      sound_speed: 1500.
      sound_speed_actual: 1482.42
    method:
      leading_edge: True
      falling_edge: False
    denoise:
      standard: True
      open: 0
      RANSAC: True
      MAD: False
    output:
      topic: "/blueview/point2/leading"
      frame_id: "blueview"